

// 1. What is a call stack?
// 2. Tell us about Try-catch?
// 3. Name some console APIs.
// 4. What is syntax error?
// 5. When do we get reference error?
// 6. a) what is wrong with the code below:
//         var foo;
//         console.log(foo.bar);
//     b) What type of error will the code generate?
//     c) What is the correct way to write the code?

// Q-1--------------------------

// A call stack is a mechanism for an interpreter (like the JavaScript interpreter in a web browser) to keep track of its place in a script that calls multiple functions — what function is currently being run and what functions are called from within that function, etc.


        function greeting() {
            sayHi();
      
        }
        function sayHi() {
             return "Hi!";
        }

        greeting();


//--------------------     Q-2             --------------------------

 
// The try...catch statement is comprised of a try block and either a catch block, a finally block, or both. The code in the try block is executed first, and if it throws an exception, the code in the catch block will be executed. The code in the finally block will always be executed before control flow exits the entire construct.


// The try statement allows you to define a block of code to be tested for errors while it is being executed. The catch statement allows you to define a block of code to be executed, if an error occurs in the try block.

posno 
//--------------------     Q-3           --------------------------
console.assert()      
console.clear()
console.count()
console.countReset()
console.debug()
console.dir()
console.dirxml()
console.error()
console.group()
console.groupCollapsed()
console.groupEnda()
console.info()
console.log()
console.table()
console.time()
console.timeEnd()
console.timeLog()
console.timeStamp()
console.trace()
console.warn()
console.profile()
console.profileEnd()
console.trace()

posno 
//--------------------     Q-4         --------------------------

// Syntax errors are mistakes in the source code, such as spelling and punctuation errors, incorrect labels, and so on, which cause an error message to be generated by the compiler. These appear in a separate error window, with the error type and line number indicated so that it can be corrected in the edit window.


// When developing programs there are three types of error that can occur: syntax errors. logic errors. runtime errors

posno 
// ------------------ Q-5-------------------------

// The ReferenceError object represents an error when a variable that doesn't exist (or hasn't yet been initialized) in the current scope is referenced

// ------------------             Q-6          -------------------------

var foo;
// console.log(foo.bar);           ///   typeError

// Code Generation Error Messages. Code Generation messages are output when the Compiler is producing generated code. Some are environment dependent ...



// 11 Tips That Will Help You Write Better Code

// 1) Decide on the indentation and keep it that way. ...
// 2) Make comments. ...
// 3) Consistent name scheme. ...
// 4) Don't repeat code. ...
// 5) Avoid writing long code lines. ...
// 6) Break down a big task into smaller chunks. ...
// 8) Write clever code that is also readable. ...
// 10) Delete unnecessary code.
